version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

  django:
    build: ./web
    command: gunicorn atlaspatchserver.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./web:/app
      - certs:/certs:ro      # server & CA certs
    environment:
      DJANGO_SECRET_KEY: 'CHANGE_ME'
      DJANGO_ALLOWED_HOSTS: '*'
      DJANGO_DEBUG: '0'
      DATABASE_URL: 'postgres://postgres:postgres@postgres:5432/postgres'
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:1.29-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/certs:ro
    ports:
      - "443:443"
    depends_on:
      django:
        condition: service_healthy

volumes:
  postgres_data:
  certs: